import Layout from "@/components/Layout";
import uuid from "react-uuid";
import Head from "next/head";
import MovieCard from "@/components/MovieCard";
import { useShow } from "@/components/ShowProvider";
import BookmarkMovie from "@/components/BookmarkMovie";
import BookmarkSeries from "@/components/BookmarkSeries";

const Bookmarks = () => {
  return (
    <>
      <Head>
        <title>EntertainHub | Bookmarks</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="showListContainer">
          <BookmarkMovie />
          <BookmarkSeries />
        </div>
      </Layout>
    </>
  );
};

export default Bookmarks;

// const bookmarkedCollection = data.filter((item) => item.isBookmarked);
// const data = showCollection.collection;
// const { bookmark } = useShow;

// const bookmarkedCollection = data.filter(
//   (item, index) => bookmark[index].bookmarkStatus
// );
// const bookmarkedMovies = bookmarkedCollection.filter(
//   (item) => item.category === "Movie"
// );
// const bookmarkedSeries = bookmarkedCollection.filter(
//   (item) => item.category === "TV Series"
// );
