import React from "react";
import Layout from "@/components/Layout";
import Head from "next/head";
import uuid from "react-uuid";
import MovieCard from "@/components/MovieCard";
import { useShow } from "@/components/ShowProvider";

const TvSeries = () => {
  const { data } = useShow();
  const seriesCollection = data.filter((item) => item.category === "TV Series");

  return (
    <>
      <Head>
        <title>EntertainHub | TV-Series</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="showListContainer">
          <div class="sectionWrapper">
            <h1 className="padding-inline fs-l-primary-heading fw-light">
              TV Series
            </h1>
            <div className="showCardContainer | padding-inline padding-block-top padding-block-bottom">
              {seriesCollection.map((item) => (
                <MovieCard show={item} key={uuid()} />
              ))}
            </div>
          </div>
        </div>
      </Layout>
    </>
  );
};

export default TvSeries;
