import React from "react";
import Link from "next/link";
import Head from "next/head";

const SignUp = () => {
  return (
    <>
      <Head>
        <title>EntertainHub | Signup</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <svg width="33" height="27" xmlns="http://www.w3.org/2000/svg">
          <path
            d="m26.463.408 3.2 6.4h-4.8l-3.2-6.4h-3.2l3.2 6.4h-4.8l-3.2-6.4h-3.2l3.2 6.4h-4.8l-3.2-6.4h-1.6a3.186 3.186 0 0 0-3.184 3.2l-.016 19.2a3.2 3.2 0 0 0 3.2 3.2h25.6a3.2 3.2 0 0 0 3.2-3.2V.408h-6.4Z"
            fill="#FC4747"
          />
        </svg>
        <section className="bg-primary-600">
          <h1 className="fs-l-primary-heading fw-light">Sign Up</h1>
          <form action="GET">
            <input
              type="email"
              name="email"
              id="email"
              className="bg-primary-600 text-neutral-100 fs-m-body fw-light"
              placeholder="Email address"
              required
            />
            <input
              type="password"
              name="password"
              id="password"
              className="bg-primary-600 text-neutral-100 fs-m-body fw-light"
              placeholder="Password"
              required
            />
            <input
              type="password"
              name="password-repeat"
              id="password-repeat"
              className="bg-primary-600 text-neutral-100 fs-m-body fw-light"
              placeholder="Repeat password"
              required
            />
            <button type="submit" className="bg-accent">
              Create an account
            </button>
          </form>
          <p className=" text-neutral-100 fs-m-body fw-light">
            Already have an account?{" "}
            <Link href="/login" className="text-accent">
              Login
            </Link>
          </p>
          <Link href="/">Go back</Link>
        </section>
      </main>
    </>
  );
};

export default SignUp;
