import React from "react";
import Head from "next/head";
import Layout from "@/components/Layout";
import MovieCard from "@/components/MovieCard";
import styles from "@/styles/Movies.module.css";
import { useShow } from "@/components/ShowProvider";
import uuid from "react-uuid";

const Movies = () => {
  const { data } = useShow();
  const movieCollection = data.filter((item) => item.category === "Movie");

  return (
    <>
      <Head>
        <title>EntertainHub | Movies</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="showListContainer">
          <h1 className="padding-inline fs-l-primary-heading fw-light">
            Movies
          </h1>
          <div className="showCardContainer | padding-inline padding-block-top padding-block-bottom">
            {movieCollection.map((item) => (
              <MovieCard show={item} key={uuid()} />
            ))}
          </div>
        </div>
      </Layout>
    </>
  );
};

export default Movies;
