import Head from "next/head";
// import styles from "@/styles/Home.module.css";
// import { initializeApp } from "firebase/app";
// import { getFirestore, collection, getDocs } from "firebase/firestore/lite";
import Layout from "@/components/Layout";
import Trending from "@/components/Trending";
import Recommendations from "@/components/Recommendations";
import ShowProvider, { useShow } from "@/components/ShowProvider";

export default function Home() {
  const { data } = useShow();
  // const firebaseConfig = {
  //   apiKey: "AIzaSyBMgBsugSNLcnuOotcRARkTvnbQaGQiOGo",
  //   authDomain: "nextjs-practice-e4f7d.firebaseapp.com",
  //   projectId: "nextjs-practice-e4f7d",
  //   storageBucket: "nextjs-practice-e4f7d.appspot.com",
  //   messagingSenderId: "385984933737",
  //   appId: "1:385984933737:web:9339b09b134954702957f8",
  // };

  // // Initialize Firebase
  // const app = initializeApp(firebaseConfig);

  // const db = getFirestore(app);

  // async function getCities(db) {
  //   const movies = collection(db, "movies");
  //   const citySnapshot = await getDocs(movies);
  //   const cityList = citySnapshot.docs.map((doc) => doc.data());
  // }

  // getCities(db);

  return (
    <>
      <Head>
        <title>EntertainHub | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="showListContainer ">
          <Trending />
          <Recommendations />
        </div>
      </Layout>
    </>
  );
}
